### PR TITLE
Update Version.

### PR DESCRIPTION
**Pull request by RockerHX**
Update PandoraPlayer.podspec for run success. and remove error: Module compiled with Swift 4.0.2 cannot be imported in Swift 4.1.2

### CODE REVIEW

**Comment by shmiftari** [comment]
Still now working

**Comment by shmiftari** [comment]
Still not working.

**Comment by shmiftari** [comment]
Hey RockerHX, it's saying Build Succeeded but is not running the app! Could you please tell me what i'm doing wrong?

**Comment by RockerHX** [comment]
@shmiftari I know, I guess you should add play list.
And how to fixed(Module compiled with Swift 4.0.2 cannot be imported in Swift 4.1.2) ?

**Comment by shmiftari** [comment]
@RockerHX  you should go to Xcode->Preferences-Components and there you should add Swift 4.0.2
Let me know if it works..
screen shot 2018-07-10 at 11 14 54

**Comment by RockerHX** [comment]
I don't see your screenshot in Xcode->Preferences-Components.
This is mine.
image

**Comment by shmiftari** [comment]
https://swift.org/download/ in thins link you should go and download only Toolchains not xcode
screen shot 2018-07-10 at 11 37 56

**Comment by RockerHX** [comment]
@shmiftari Perfect, build success.

Run crash, code:
```
        let playerVC = PandoraPlayer.configure(withAVItems: [AVPlayerItem]())
        navigationController?.present(playerVC, animated: true, completion: nil)
```

But what the fuck:
```
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /xx/xxx/Library/Developer/CoreSimulator/Devices/CF0BE840-3027-4B01-B724-BD6AE727FC17/data/Containers/Bundle/Application/3ED06A2A-91CB-41E9-BC39-0811E7E555AB/PandoraPlayerDemo.app/Frameworks/AudioKit.framework/AudioKit
  Reason: Incompatible library version: AudioKit requires version 1.0.0 or later, but libswiftAVFoundation.dylib provides version 0.0.0
```

**Comment by shmiftari** [comment]
@RockerHX did you find any solution ?

**Comment by RockerHX** [comment]
@shmiftari No, I guess use swift 4.0.3 is't package libswiftAVFoundation.dylib to ipa...

**Comment by RockerHX** [comment]
@shmiftari success!!!

image

Demo:
[PandoraPlayerDemo.zip](https://github.com/ApplikeySolutions/PandoraPlayer/files/2181064/PandoraPlayerDemo.zip)

**Comment by shmiftari** [comment]
@RockerHX Great! Which version of Xcode are you using?

**Comment by RockerHX** [comment]
@shmiftari Xcode Version 9.4.1 (9F2000): Swift 4.1.2

**Comment by shmiftari** [comment]
@RockerHX Thanks man! Is working.. I wanna know if you try to put in a collection the list of music and play with them?

**Comment by RockerHX** [comment]
@shmiftari 😊

**Comment by mahadshahib** [comment]
Guys can you explane to me exactly what you have done to run this? I really need it  i installed toolchain and error goes away but how did you exactly handle run crash error?

**Review by mahadshahib — CHANGES_REQUESTED** [review]
please please change this i really need it please

**Comment by letam245** [comment]
hello, could you please let me know the steps I need to do to able to run this the app? I download the demo zip file and added in the pod 'PandoraPlayer' in pod file, when I run it, I have the error as screenshots. I currently use Xcode Version 10.0 (10A255) and swift 4 for language (build setting) and I only have Xcode 10.0 (10a255) the only choice I have in the command line tools, same with my toolchain, only Xcode 10.0. Please help! thanks a ton
screen shot 2018-10-16 at 9 15 14 am
screen shot 2018-10-16 at 9 20 47 am
screen shot 2018-10-16 at 9 45 30 am

**Pull request closed without merging**
